# Generated by Django 5.0.6 on 2024-05-15 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(verbose_name='Время начала тестирования')),
                ('time_end', models.DateTimeField(verbose_name='Время конца тестирования')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='group.group', verbose_name='Группа')),
                ('testing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testing', to='testing.testing', verbose_name='Тестирование')),
            ],
            options={
                'verbose_name': 'Настройки работы теста',
                'verbose_name_plural': 'Настройки работы теста',
                'ordering': ['created_at'],
            },
        ),
    ]
