# Generated by Django 5.0.6 on 2024-05-15 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500, verbose_name='Текст вопроса')),
                ('ball', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Балл за правильный ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('testing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testing.testing', verbose_name='Тестирование')),
            ],
            options={
                'verbose_name': 'Вопросы',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['created_at'],
            },
        ),
    ]
