# Generated by Django 5.0.6 on 2024-05-15 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Текст варианта ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильность ответа')),
                ('ball', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Балл за правильный ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='question.question', verbose_name='Вопросы')),
            ],
            options={
                'verbose_name': 'Варианты ответов',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['created_at'],
            },
        ),
    ]
